services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${POSTGRES_HOST}
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT_EXPOSE:-5432}:5432"
    volumes:
      - "./data/postgresql/data:/var/lib/postgresql/data"
    networks:
      - internal
networks:
  internal:
    external: true